# Generated by Django 3.2.25 on 2025-12-16 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='genre',
        ),
        migrations.AddField(
            model_name='interaction',
            name='content',
            field=models.TextField(blank=True, help_text='Only required if the interaction type is COMMENT.', null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('LOVE', 'Love'), ('LIKE', 'Like'), ('COMMENT', 'Comment')], max_length=7),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='review_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core_db.reviewpost'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core_db.book'),
        ),
        migrations.AddField(
            model_name='reviewpost',
            name='reviewer_genres',
            field=models.ManyToManyField(blank=True, related_name='reviews_by_opinion', to='core_db.Genre'),
        ),
    ]
