# Generated by Django 3.2.25 on 2025-12-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0002_auto_20251216_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core_db.book'),
            preserve_default=False,
        ),
    ]
