# Generated by Django 3.2.25 on 2025-12-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0003_alter_reviewpost_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
