# Generated by Django 3.2.25 on 2026-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0004_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
