# Generated by Django 3.2.25 on 2026-01-26 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0005_genre_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LOVE', 'Love'), ('LIKE', 'Like')], max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='review_post',
        ),
        migrations.RemoveField(
            model_name='reviewpost',
            name='reviewer_genres',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='core_db.Genre'),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='review_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name='reviewpost',
            constraint=models.UniqueConstraint(fields=('reviewer', 'book'), name='unique_review_per_user_per_book'),
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.AddField(
            model_name='reaction',
            name='review_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core_db.reviewpost'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='review_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core_db.reviewpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'review_post'), name='unique_user_reaction'),
        ),
    ]
